### ISSUE TITLE
Any plans for moving to Symf 3.1?

### ISSUE THREAD

**Issue by CristianSitov** [chalasr/RCHJWTUserBundle#7]
I'm working on a small project built around Symf 3.1 and current dependency limits installation to 3.0

**Comment by CristianSitov** [comment]
Found a working combination:
```yaml
    "minimum-stability": "dev",
    "require": {
        ...
        "rch/jwt-user-bundle": "dev-restrict_fosuser"
        ...
```
but this implies, as seen above, a change in the minimum stability. :)
